on:
  push:

jobs:
  deploy-clojars:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Leiningen
        uses: DeLaGuardo/setup-clojure@3.5
        with:
          lein: 2.9.7

      - name: Deploy
        uses: jlesquembre/clojars-publish-action@0.3
        env:
          CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
          CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
