on:
  push:
    tags:
      - 'v*'

jobs:
  deploy-clojars:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Leiningen
        uses: DeLaGuardo/setup-clojure@3.5
        with:
          lein: 2.9.7

      - name: Deploy
        env:
          CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
          CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
        run: |
          lein deploy clojars
